version: '2'

services:

    abp_mvc:
        image: dockerusername/mvc
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
        ports:
            - "9903:44311"
        volumes:
            - "./Mvc-Logs:/app/App_Data/Logs"